### ISSUE TITLE
Create seeder for nutritional_restrictions table

### ISSUE THREAD

**Issue by fjborquez** [fjborquez/aang#17]
**As a** Data owner
**I want to** populate the system with nutritional restrictions
**So that** I can create different users restrictions profiles

### Scope
> 1. Add nutritional restrictions.

### Out of scope
> 1. Create default profiles.

### Result
The table is populated with different nutritional restrictions.

**Comment by Norbbs** [comment]
@fjborquez Add:
Dairy-free
Gluten-free
Wheat-free
Nut-free
Soy-free
Egg-free 
Shellfish-free 
Fish-free 
Pork-free 
Red meat-free 
Caffeine-free
Alcohol-free 
Spicy food-free
Peanut allergy

**Comment by fjborquez** [comment]
@Norbbs done!
