### ISSUE TITLE
Bug Template

### ISSUE THREAD

**Issue by Norbbs** [fjborquez/aang#8]
**As a** Data Owner
**I want to** Register Data User Manually
**So that** I ensure secure login and authentication

### Definition Of Ready (DoR)
|   | **Definition**                                   |  **Observations**  |
|---|----------------------------------------------|---|
|  <ul><li>- [ ] </li></ul> | Story where the bug was identified or an easy way to reproduce                                            | #2 AC3  |
|  <ul><li>- [ ] </li></ul> | Environment (Dev, Test, Prod)                                                    |    |
|  <ul><li>- [ ] </li></ul> | Severity (Low, Medium, High)                                                    |  Low  |

### Bug Description
When attempting to register a user, the system allows an incorrect format for the user's name and last name, not allowing spaces.

### Steps to Reproduce
> 1. Fill in the registration form with the user's name and last name.
> 2. Include one or more spaces in either the name or last name field.
> 3. Click on the register button to submit the form.

### Expected Behavior
The system should validate the format of the user's name and last name, allowing any input that includes **ONLY ONE SPACE**. 

### Actual Behavior
The system doesn't allow registration even if the name or last name field includes one o more spaces, violating the acceptance criteria.

### Impact
Not allowing one space in the name and last name fields could exclude some users. 

### [IMPORTANT]: Only one blank space must be allow it, not more than that.

**Comment by fjborquez** [comment]
I'm thinking that it should accept more than one space. There are lastnames like "De la Carrera", "De la Fuente"

**Comment by Norbbs** [comment]
Agree with you but not consecutive spaces @fjborquez
